"""empty message

Revision ID: 11678d2494f4
Revises: 5e5a9f101d3a
Create Date: 2025-09-13 00:41:21.148910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11678d2494f4'
down_revision = '5e5a9f101d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
