"""empty message

Revision ID: 5e5a9f101d3a
Revises: ef6ddc501cbe
Create Date: 2025-09-13 00:25:05.710724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5a9f101d3a'
down_revision = 'ef6ddc501cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('publisher', sa.String(length=80), nullable=False),
    sa.Column('introduction', sa.String(length=200), nullable=True),
    sa.Column('ISBN', sa.String(length=13), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ISBN')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index('idx_book_ISBN', ['ISBN'], unique=False)
        batch_op.create_index('idx_book_author', ['author'], unique=False)
        batch_op.create_index('idx_book_name', ['name'], unique=False)
        batch_op.create_index('idx_book_publisher', ['publisher'], unique=False)

    op.create_table('borrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('borrow_time', sa.DateTime(), nullable=False),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.create_index('idx_borrow_book_id', ['book_id'], unique=False)
        batch_op.create_index('idx_borrow_status', ['status'], unique=False)
        batch_op.create_index('idx_borrow_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('privilege', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('sex', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('introduction', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_phone', ['phone'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=False)
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_phone')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('introduction')
        batch_op.drop_column('age')
        batch_op.drop_column('sex')
        batch_op.drop_column('name')
        batch_op.drop_column('privilege')
        batch_op.drop_column('password')
        batch_op.drop_column('phone')

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_index('idx_borrow_user_id')
        batch_op.drop_index('idx_borrow_status')
        batch_op.drop_index('idx_borrow_book_id')

    op.drop_table('borrow')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index('idx_book_publisher')
        batch_op.drop_index('idx_book_name')
        batch_op.drop_index('idx_book_author')
        batch_op.drop_index('idx_book_ISBN')

    op.drop_table('book')
    # ### end Alembic commands ###
