"""empty message

Revision ID: d9fb3618b093
Revises: 2636f033bdcb
Create Date: 2025-09-13 02:58:01.349932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9fb3618b093'
down_revision = '2636f033bdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=False))
        batch_op.create_index('idx_book_category', ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index('idx_book_category')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
